### ISSUE TITLE
Buttons using kbd, br and links

### ISSUE THREAD

**Issue by Kernix13** [Kernix13/markdown-cheatsheet#11]
Button with padding:

<kbd> <br> cmd + shift + p <br> </kbd>

Button as a link but no padding (wish this had padding:

<kbd>[Markdown-Cheatsheet](https://github.com/lifeparticle/Markdown-Cheatsheet)</kbd>

**Comment by lifeparticle** [comment]
Here you go, with padding:

<kbd> <br><br> [Markdown-Cheatsheet](https://github.com/lifeparticle/Markdown-Cheatsheet) <br><br>   </kbd>

<kbd> <br> [Markdown-Cheatsheet](https://github.com/lifeparticle/Markdown-Cheatsheet) <br> </kbd>


```markdown
<kbd> <br><br> [Markdown-Cheatsheet](https://github.com/lifeparticle/Markdown-Cheatsheet) <br><br>   </kbd>

<kbd> <br> [Markdown-Cheatsheet](https://github.com/lifeparticle/Markdown-Cheatsheet) <br> </kbd>
```
