### ISSUE TITLE
Incorporating Alerts into Markdown Cheatsheet

### ISSUE THREAD

**Issue by lifeparticle** [Kernix13/markdown-cheatsheet#6]
Hello @Kernix13,

I've been exploring your markdown cheatsheet and I'm really impressed with yours.

However, I noticed that the cheatsheet doesn't include information about 'alerts', a feature I recently discovered. Alerts can be quite handy for emphasizing important points or warnings in markdown documents.

Since your cheatsheet is already a great resource, I think adding a section on alerts could make it even more comprehensive and useful. 

Thanks!

**Comment by Kernix13** [comment]
I like the alerts in your cheatsheet. Wee they recently added? I went to your GitHub profile and copied your email address. I just sent you an invite to my Slack Workspace - it's name is my name, James Kernicky. If you want accept the invite and we can chat more easily in there about getting both of our cheatsheets current with all the options.

**Comment by Kernix13** [comment]
Here is what I see in our differences:

I'm missing:
1. Boxed: `<table><tr><td>The quick brown fox jumps over the lazy dog.</td></tr></table>`
2. table without `<thead>` or `<tbody>`
3. table tags with md table syntax in a td - didn't know you could do that
4. the green thing in the images section - is that just an `<img>` tag?
5. `<kbd>` with a link to simulate a button - h2 or h3 would make it bigger! (See below)
6. diagrams - Mermaid or something else?
7. ALERTS!!!
8. Sponsor button

> he has more forks and stars than my repo!?!

@lifeparticle is missing:
1. descriptions using HTML tags `<dl>`, `<dt>`, and `<dd>` for indentation
2. code blocks with md as the language as the code examples
3. frontmatter 
4. footnotes links
5. other options for code block: TAB, generic, quads
6. Diff code blocks
7. Discord spoiler text
8. Shields.io badges
10. Devicons
11. Mermaid diagrams (or is that the Diagrams section?)
12. HTML entities

> Mentions Bitbucket but not GitLab

> maybe more code block syntax examples without scroll bars

So I can push anything that I have that you would want to your repo, and you could do the opposite for my repo. We would just have to coordinate where we want that new code/content.

**Comment by Kernix13** [comment]
FYI, your title with the black circles would use an `<h>` tag IMO

**Comment by lifeparticle** [comment]
Hi, thank you for taking the time and listing out all the items, I really appreciate that!

> We would just have to coordinate where we want that new code/content.

That sounds like a great idea.

**Comment by lifeparticle** [comment]
> FYI, your title with the black circles would use an `<h>` tag IMO

Thanks, done!

**Comment by lifeparticle** [comment]
> I like the alerts in your cheatsheet. Wee they recently added? I went to your GitHub profile and copied your email address. I just sent you an invite to my Slack Workspace - it's name is my name, James Kernicky. If you want accept the invite and we can chat more easily in there about getting both of our cheatsheets current with all the options.

Yes, it was around added in last [December](https://github.blog/changelog/2023-12-14-new-markdown-extension-alerts-provide-distinctive-styling-for-significant-content/).

Thank you, I got your invite and accepted it. Looking forward to working with you!

**Comment by Kernix13** [comment]
The alerts look great, thanks for the contribution!
